added webroot flag, carrying it with settings to router and added some valid and directory traversal tests

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -5,6 +5,9 @@ fail() {
    exit 1
 }
 
+mkdir -p tmp/webroot
+echo "Hello, world!" > tmp/webroot/hello.txt
+
 test -z "$@" && fail "opus startup command needed as argument(s)"
 
 for pid in $(pgrep -f 'ol --run opus')
@@ -14,9 +17,13 @@ do
    sleep 1
 done
 
-$@ --ephemereal -U test -P pass -p 9000 &
+$@ --ephemereal -U test -P pass -p 9000 --webroot tmp/webroot &
 
-python test/usage.py || { kill -9 %1; exit 1; }
+# close on errors
+# python test/usage.py || { kill -9 %1; exit 1; }
+
+# leave running
+python test/usage.py || exit 1
 
 kill -9 %1 || true
 
